name: xonotic
version: '0.8.6'
summary: The Free and Fast Arena Shooter
description: |
 Xonotic is an addictive, arena-style first person shooter with crisp movement
 and a wide array of weapons. It combines intuitive mechanics with in-your-face
 action to elevate your heart rate. Xonotic is and will always be free-to-play.
base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - amd64
  - arm64

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

apps:
  dedicated:
    extensions: [gnome]
    command: Xonotic/xonotic-dedicated -basedir /snap/xonotic/current/Xonotic
    plugs:
      - network
      - network-bind

  xonotic:
    extensions: [gnome]
    command: Xonotic/xonotic-sdl -basedir /snap/xonotic/current/Xonotic
    environment:
      SDL_AUDIODRIVER: pulse
    plugs:
      - audio-playback
      - joystick
      - network
      - network-bind
      - opengl
      - optical-drive
      - wayland
      - x11

parts:
  xonotic:
    plugin: dump
    source: https://dl.xonotic.org/xonotic-$SNAPCRAFT_PROJECT_VERSION-source.zip
    override-build: |
      (cd Xonotic && make both)

      install -Dm755 Xonotic/source/darkplaces/darkplaces-dedicated "$SNAPCRAFT_PART_INSTALL"/Xonotic/xonotic-dedicated
      install -Dm755 Xonotic/source/darkplaces/darkplaces-sdl "$SNAPCRAFT_PART_INSTALL"/Xonotic/xonotic-sdl

      (cd Xonotic/source/d0_blind_id && make DESTIR="$SNAPCRAFT_PART_INSTALL" install)
    build-packages:
      - automake
      - libtool
      - libgmp-dev
      - libjpeg-turbo8-dev
      - libsdl2-dev
      - libxpm-dev
      - zlib1g-dev
    stage-packages:
      - libasound2
      - libbsd0
      - libgcc1
      - libsdl2-2.0-0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxxf86vm1
      - zlib1g
  xonotic-data:
    plugin: dump
    source: https://dl.xonotic.org/xonotic-$SNAPCRAFT_PROJECT_VERSION.zip
    prime:
      - -Xonotic/Xonotic.app/
      - -Xonotic/*.exe
      - -Xonotic/bin32
      - -Xonotic/bin64
      - -Xonotic/Docs
      - -Xonotic/misc
      - -Xonotic/server/rcon2irc
      - -Xonotic/source
      - -Xonotic/xonotic-linux*
      - -Xonotic/xonotic-osx-dedicated
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
