name: xonotic
version: '0.8.6'
summary: The Free and Fast Arena Shooter
description: |
 Xonotic is an addictive, arena-style first person shooter with crisp movement
 and a wide array of weapons. It combines intuitive mechanics with in-your-face
 action to elevate your heart rate. Xonotic is and will always be free-to-play.
base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

apps:
  dedicated:
    extensions: [gnome]
    command: Xonotic/xonotic-linux64-dedicated -basedir /snap/xonotic/current/Xonotic
    plugs:
      - network
      - network-bind

  xonotic:
    extensions: [gnome]
    command: Xonotic/xonotic-linux64-sdl -basedir /snap/xonotic/current/Xonotic
    environment:
      SDL_AUDIODRIVER: pulse
    plugs:
      - audio-playback
      - joystick
      - network
      - network-bind
      - opengl
      - optical-drive
      - wayland
      - x11

parts:
  xonotic:
    plugin: dump
    source: http://dl.xonotic.org/xonotic-$SNAPCRAFT_PROJECT_VERSION.zip
    build-packages:
      - dpkg
    stage-packages:
      - libasound2
      - libbsd0
      - libgcc1
      - libsdl2-2.0-0
      - libstdc++6
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxxf86vm1
      - zlib1g
    prime:
      - -Xonotic/Xonotic.app/
      - -Xonotic/*.exe
      - -Xonotic/bin32
      - -Xonotic/bin64
      - -Xonotic/Docs
      - -Xonotic/misc
      - -Xonotic/server/rcon2irc
      - -Xonotic/source
      - -Xonotic/xonotic-linux*-glx*
      - -Xonotic/xonotic-osx-dedicated
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
